dependencies:
  - name: microservice
    version: 0.1.0
    repository: "file://../microservice"
    alias: auth
    condition: auth.enabled
  - name: microservice
    version: 0.1.0
    repository: "file://../microservice"
    alias: user
    condition: user.enabled
  - name: microservice
    version: 0.1.0
    repository: "file://../microservice"
    alias: pubsub
    condition: pubsub.enabled
  - name: microservice
    version: 0.1.0
    repository: "file://../microservice"
    alias: pushpull
    condition: pushpull.enabled
  # AWS localstack (for local development)
  - name: microservice
    version: 0.1.0
    repository: "file://../microservice"
    alias: localstack
    condition: localstack.enabled
  - name: microservice
    version: 0.1.0
    repository: "file://../microservice"
    alias: maildev
    condition: maildev.enabled
  # External charts: https://github.com/helm/charts/blob/master/stable
  - name: cert-manager
    version: v0.15.1
    repository: https://charts.jetstack.io # `helm repo add jetstack https://charts.jetstack.io`
    condition: cert-manager.enabled
  - name: nginx-ingress
    version: 1.39.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: nginx-ingress.enabled
  - name: mysql
    version: 1.6.4
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mysql.enabled
  - name: phpmyadmin
    version: 6.2.0
    repository: https://charts.bitnami.com/bitnami # `helm repo add bitnami https://charts.bitnami.com/bitnami`
    condition: phpmyadmin.enabled
